name: Context testing
on: push

permissions:
  contents: read
  pull-requests: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  dump_contexts_to_log:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9"]
        graphviz-version: ["0.20"]
        torch-version-map: [
          {torch: "1.13", torchvision: "0.14", torchtext: "0.14"},
        ]
    steps:
      - uses: actions/checkout@v2.5.0
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
      - name: Dump context path
        run: echo $GITHUB_ACTIONS
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4.3.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install mypy pytest pytest-cov numpy
          pip install graphviz==${{ matrix.graphviz-version }}
          pip install torch==${{ matrix.torch-version-map.torch }} \
            torchvision==${{ matrix.torch-version-map.torchvision }} \
            torchtext==${{ matrix.torch-version-map.torchtext }}
          pip install torchview
          echo $RUNNER_OS
        shell: bash
      - name: pytest
        run: |
          pytest --cov=dummy_package --cov-report= --durations=0
      - name: codecov
        uses: codecov/codecov-action@v3.1.1
